apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: main-domain-cert
  namespace: voyager
spec:
  domains:
  - example.e28.dev
  - mqtt.e28.dev
  acmeUserSecretName: acme-account
  challengeProvider:
    dns:
      provider: digitalocean
      credentialSecretName: do-dns-secret
  storage:
    secret:
      name: cert-main-domain
