apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: example-engelbrink-dev-cert
  namespace: default
spec:
  domains:
  - example.engelbrink.dev
  acmeUserSecretName: acme-account
  challengeProvider:
    dns:
      provider: digitalocean
      credentialSecretName: do-dns-secret
  storage:
    secret:
      name: cert-example-engelbrink-dev