apiVersion: voyager.appscode.com/v1beta1
kind: Certificate
metadata:
  name: engelbrink-dev
  namespace: http
spec:
  domains:
  - engelbrink.dev
  - example.engelbrink.dev
  - mqtt.engelbrink.dev
  acmeUserSecretName: acme-account
  challengeProvider:
    dns:
      provider: digitalocean